# This is a basic workflow to help you get started with Actions
#Not required

name: hello

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #All events are here:
    #https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    #possible event triggers:
    #push - when code added to the repository, only in branch "main"
    #pull_request
    #release
    #workflow_dispatch - Allows you to run this workflow manually from the Actions tab
    #Webhooks - GitHub webhooks, events associated with the repo, but not directly to the code change (Branch creation, 
      #Issues, membership changes)
    #Scheduled - for run at specific date and time, Cron format
    #for multiple events square brackets should be used:
    #[push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# At least one job is required

jobs:
  # This workflow contains a single job called "job1", 
    #can be used any identifier (only digits, letters, underscore and dash are allowed, 
    #identifier must start with underscore or letter)
    #Jobs run in parallel by default
  job1:
    # The type of runner that the job will run on
      #possible runners:
        #Windows Server (windows-latest)
        #Ubuntu (ubuntu-latest)
        #macOS (macos-latest)
        #Self-hosted runners
    name: first Job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # - uses: is used for actions
    # run: is used for commands (default shell is Bash for Ubuntu and macOS and PowerShell for windows)
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #uses attribute identifies an action to use, Defines the location of that action
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script #name attribute is not required, can be used with "uses" and "run" attributes
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Print workspace
        run: echo $GITHUB_WORKSPACE

      - name: TestStep
        run: env | sort

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
